version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_SECRET_KEY=your-secret-key
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1

volumes:
  static_volume:
